## AudioKit.gd - procedural audio autoload for NEXUS ARCADE v0.8.0.
## Every SFX and music loop is synthesized at build time by tools/gen_audio.py
## (numpy/scipy; zero licensed assets, zero legal risk). SFX are preloaded once
## into a small pool; music loops stream from disk one at a time so they never
## all sit in RAM. Volumes persist in user://nexus_settings.cfg [audio].
extends Node

const SFX_DIR := "res://assets/audio/sfx/"
const MUSIC_DIR := "res://assets/audio/music/"
const SETTINGS_PATH := "user://nexus_settings.cfg"
const POOL_SIZE := 8
const POOL_3D_SIZE := 4  # positional SFX voices (TECH_DEMO_PLAN §6 budget)
const DUCK_DB := 5.0      # how far the music dips during an SFX burst
const DUCK_WINDOW := 0.6  # >=3 SFX inside this window counts as a burst
const DUCK_HOLD := 0.6    # seconds to hold the duck after a burst

## Stinger kinds -> SFX names (play_stinger).
const STINGERS := {
	"success": "success", "fail": "fail", "levelup": "fanfare",
	"boss": "buzzer", "notify": "notify", "unlock": "unlock",
	"countdown": "countdown", "gameover": "fail",
}

const SFX_NAMES: Array[String] = [
	"ui_click", "ui_hover", "ui_back", "success", "fail", "pop", "coin",
	"whoosh", "explosion", "splash", "laser", "thud", "sparkle",
	"countdown", "whistle", "buzzer", "powerup", "jump", "land", "shoot",
	"hit", "heal", "unlock", "door", "chest", "bubble", "zap", "fanfare",
	"notify", "error",
	# v0.9.1: seamless jet-roar loop for Sky Traffic (looping ambient, not a
	# one-shot; generated by tools/gen_audio.py LOOPS).
	"engine_roar",
]

const GENRES: Array[String] = [
	"chiptune", "horror", "tropical", "western", "underwater", "epic",
	"lofi", "carnival", "scifi", "folk", "menu_theme",
]

## Per-game music genre, keyed by scene file stem (source of truth: the
## CAT_GAMES / CAT_UTILITIES / CAT_CREATE / CAT_THEMES lists in hub.gd).
const GENRE_FOR_SCENE := {
	# -- CAT_GAMES --
	"golf": "folk", "swarm": "scifi", "duel": "epic",
	"ar-defender": "scifi", "sky-defender": "epic", "drone-racer": "scifi",
	"ar-fishing": "underwater", "mirror-maze": "scifi",
	"air-drums": "chiptune", "shadow-puppet": "carnival",
	"ar-escape-room": "horror", "ar-billiards": "lofi",
	"holo_chef": "folk", "dragon_ranch": "epic",
	"wizard_academy": "epic", "holo_farm": "folk", "mech_pilot": "scifi",
	"deep_dive": "underwater", "ar_detective": "lofi",
	"sky_pirates": "tropical", "monster_lab": "horror", "myth_zoo": "epic",
	"qr_hunt": "western",
	# -- CAT_UTILITIES --
	"sky_traffic": "lofi", "eye_spy": "lofi", "plant_doctor": "folk",
	"mano_magica": "folk",
	# -- CAT_CREATE --
	"holo-piano": "lofi", "holo-theremin": "scifi",
	"graffiti-wall": "chiptune", "ar-karaoke": "carnival",
	"sand-shaper": "lofi", "clay-shaper": "folk", "sketch_3d": "lofi",
	"holo-garden": "folk", "zero-g-sandbox": "scifi",
	"holo-aquarium": "underwater",
	# -- CAT_THEMES (halloween) --
	"hw_web_slingshot": "horror", "hw_potion_mix": "horror",
	"hw_monster_mash": "horror", "hw_candy_stack": "horror",
	"hw_mummy_wrap": "horror", "hw_bat_dodge": "horror",
	"hw_pumpkin_carve": "horror", "hw_portrait_gallery": "horror",
	"hw_apple_bobbing": "horror", "hw_phantom_piano": "horror",
	"hw_goblin_archery": "horror", "hw_mirror_maze": "horror",
	"hw_monster_feed": "horror", "hw_midnight_survival": "horror",
}

var sfx_volume := 0.8
var music_volume := 0.8
var sfx_enabled := true
var music_enabled := true

var _sfx: Dictionary = {}
var _pool: Array[AudioStreamPlayer] = []
var _pool_idx := 0
var _pool3d: Array[AudioStreamPlayer3D] = []
var _pool3d_idx := 0
var _music: AudioStreamPlayer
var _current_genre := ""
var _sfx_times: Array[float] = []
var _duck_until := 0.0
var _duck_level := 0.0
# v0.9.0: per-game SFX registration + intensity layer.
var _game_sfx: Dictionary = {}  # scene_stem -> {name -> AudioStream}
var _active_scene := ""
var _intensity := 0
var _drive: AudioStreamPlayer = null  # intensity overlay loop (synthesized)


func _ready() -> void:
	_music = AudioStreamPlayer.new()
	_music.name = "AudioKitMusic"
	add_child(_music)
	for i in POOL_SIZE:
		var p := AudioStreamPlayer.new()
		p.name = "AudioKitSFX%d" % i
		add_child(p)
		_pool.append(p)
	for i in POOL_3D_SIZE:
		var p3 := AudioStreamPlayer3D.new()
		p3.name = "AudioKitSFX3D%d" % i
		p3.max_distance = 12.0
		p3.attenuation_model = AudioStreamPlayer3D.ATTENUATION_INVERSE_SQUARE_DISTANCE
		add_child(p3)
		_pool3d.append(p3)
	_load_settings()
	# v0.9.3: SFX streams load LAZILY on first play via _ensure_sfx() (the
	# old 31-synchronous-wav-load loop stalled the boot thread; Stage 0 must
	# stay light). The player pools are the only boot cost now.


func _process(_delta: float) -> void:
	if _music == null:
		return
	var now := Time.get_ticks_msec() / 1000.0
	var target := DUCK_DB if now < _duck_until else 0.0
	_duck_level = lerpf(_duck_level, target, 0.25)
	_music.volume_db = _vol_db(music_volume) - _duck_level


## Load-once cache for SFX streams (v0.9.3 lazy boot). Returns null when the
## file doesn't exist; callers warn and no-op.
func _ensure_sfx(sfx_name: String) -> AudioStream:
	if _sfx.has(sfx_name):
		return _sfx[sfx_name] as AudioStream
	var path := SFX_DIR + sfx_name + ".wav"
	if ResourceLoader.exists(path):
		var s := load(path) as AudioStream
		if s != null:
			_sfx[sfx_name] = s
			return s
	push_warning("AudioKit: missing SFX " + path)
	return null


## Play a named SFX (see SFX_NAMES). Pitch and extra dB are optional.
func play_sfx(sfx_name: String, pitch := 1.0, volume_db := 0.0) -> void:
	if not sfx_enabled:
		return
	var stream := _ensure_sfx(sfx_name)
	if stream == null:
		return
	_play_stream(stream, pitch, volume_db)
	_note_sfx_burst()


func _note_sfx_burst() -> void:
	var now := Time.get_ticks_msec() / 1000.0
	_sfx_times.append(now)
	while not _sfx_times.is_empty() and now - _sfx_times[0] > DUCK_WINDOW:
		_sfx_times.pop_front()
	if _sfx_times.size() >= 3:
		_duck_until = now + DUCK_HOLD


## Play a music genre loop (see GENRES). No-op if already playing it.
func play_music(genre: String) -> void:
	if not genre in GENRES:
		push_warning("AudioKit: unknown genre '" + genre + "'")
		return
	if genre == _current_genre and _music.playing:
		return
	_current_genre = genre
	if not music_enabled:
		return
	var path := MUSIC_DIR + genre + ".wav"
	if not ResourceLoader.exists(path):
		push_warning("AudioKit: missing music " + path)
		return
	_music.stream = load(path)
	_music.volume_db = _vol_db(music_volume)
	_music.play()


func stop_music() -> void:
	_music.stop()
	_current_genre = ""


## Convenience: pick the mapped genre from a scene file stem ("holo_chef").
func play_music_for_scene(scene_key: String) -> void:
	play_music(GENRE_FOR_SCENE.get(scene_key, "lofi"))


func genre_for_scene(scene_key: String) -> String:
	return GENRE_FOR_SCENE.get(scene_key, "lofi")


func current_genre() -> String:
	return _current_genre


# --------------------------------------- v0.9.0: per-game SFX + 3D + stingers ---

## Tell AudioKit which game is active (the hub auto-wirer calls this on
## every launch). Per-game SFX maps resolve against this stem.
func set_active_scene(scene_stem: String) -> void:
	_active_scene = scene_stem


func active_scene() -> String:
	return _active_scene


## Register per-game SFX: games call this in _ready() with
## {"hit": "res://.../hit.wav", ...}. Files are loaded once here.
func register_game_sfx(scene_stem: String, map: Dictionary) -> void:
	var loaded := {}
	for sfx_name in map.keys():
		var path := str(map[sfx_name])
		if ResourceLoader.exists(path):
			loaded[str(sfx_name)] = load(path)
		else:
			push_warning("AudioKit: game SFX missing " + path)
	_game_sfx[scene_stem] = loaded


## Play a game-registered SFX for the active scene (falls back to the
## global SFX pool when the name isn't registered for this game).
func play_game_sfx(sfx_name: String, pitch := 1.0, volume_db := 0.0) -> void:
	var game_map: Dictionary = _game_sfx.get(_active_scene, {})
	if game_map.has(sfx_name):
		_play_stream(game_map[sfx_name], pitch, volume_db)
		return
	play_sfx(sfx_name, pitch, volume_db)


func _play_stream(stream: AudioStream, pitch: float, volume_db: float) -> void:
	if not sfx_enabled or stream == null:
		return
	var p := _pool[_pool_idx]
	_pool_idx = (_pool_idx + 1) % POOL_SIZE
	p.stream = stream
	p.pitch_scale = pitch
	p.volume_db = _vol_db(sfx_volume) + volume_db
	p.play()
	_note_sfx_burst()


## Positional one-shot (splash on your floor, creature behind the couch).
## Own 4-voice AudioStreamPlayer3D pool (TECH_DEMO_PLAN §6 budget).
func play_sfx_3d(sfx_name: String, pos: Vector3, pitch := 1.0, volume_db := 0.0) -> void:
	if not sfx_enabled:
		return
	var stream: AudioStream = null
	var game_map: Dictionary = _game_sfx.get(_active_scene, {})
	if game_map.has(sfx_name):
		stream = game_map[sfx_name]
	else:
		stream = _ensure_sfx(sfx_name)
	if stream == null:
		push_warning("AudioKit: unknown 3D SFX '" + sfx_name + "'")
		return
	var p := _pool3d[_pool3d_idx]
	_pool3d_idx = (_pool3d_idx + 1) % POOL_3D_SIZE
	p.stream = stream
	p.pitch_scale = pitch
	p.volume_db = _vol_db(sfx_volume) + volume_db
	p.global_position = pos
	p.play()
	_note_sfx_burst()


## Named one-shots: "success" / "fail" / "levelup" / "boss" / "notify" /
## "unlock" / "countdown" / "gameover". Checks the active game's registered
## SFX first, then the built-in stinger map.
func play_stinger(kind: String, volume_db := 0.0) -> void:
	var game_map: Dictionary = _game_sfx.get(_active_scene, {})
	if game_map.has(kind):
		_play_stream(game_map[kind], 1.0, volume_db)
		return
	var sfx_name: String = STINGERS.get(kind, "")
	if sfx_name == "":
		push_warning("AudioKit: unknown stinger '" + kind + "'")
		return
	play_sfx(sfx_name, 1.0, volume_db)


## Music intensity 0-2 (explore -> tense -> combat). Implemented as a
## synthesized percussive "drive" layer mixed under the current genre loop
## (zero new audio assets; generated once at runtime, looped).
func set_intensity(level: int) -> void:
	_intensity = clampi(level, 0, 2)
	if _intensity > 0 and _drive == null:
		_drive = AudioStreamPlayer.new()
		_drive.name = "AudioKitDrive"
		_drive.stream = _make_drive_loop()
		add_child(_drive)
	if _drive == null:
		return
	if _intensity == 0 or not music_enabled:
		_drive.stop()
		return
	if not _drive.playing:
		_drive.play()
	# Level 1: low pulse under the music. Level 2: driving.
	_drive.volume_db = _vol_db(music_volume) + (-16.0 if _intensity == 1 else -9.0)


func intensity() -> int:
	return _intensity


## 2-bar 132 BPM percussive drive loop, synthesized (kick + hats + bass
## pulse). Mono 22050 Hz, seamless loop, ~3.6s / ~160KB in RAM.
func _make_drive_loop() -> AudioStreamWAV:
	var rate := 22050
	var bpm := 132.0
	var beats := 8.0
	var n := int(rate * 60.0 / bpm * beats)
	var data := PackedByteArray()
	data.resize(n * 2)
	var beat_n := int(rate * 60.0 / bpm)
	for i in range(n):
		var t := float(i) / float(rate)
		var v := 0.0
		var in_beat := i % beat_n
		var bt := float(in_beat) / float(rate)
		# Kick on quarters: sine drop 120->40Hz, fast decay.
		var f := 40.0 + 80.0 * exp(-bt * 30.0)
		v += 0.65 * sin(TAU * f * bt) * exp(-bt * 9.0)
		# Hats on 8ths: filtered noise tick.
		var eighth := beat_n / 2
		if i % eighth < int(rate * 0.03):
			var ht := float(i % eighth) / float(rate)
			v += 0.22 * (randf() * 2.0 - 1.0) * exp(-ht * 90.0)
		# Bass pulse on off-beats.
		var half := i % (beat_n * 2)
		if half >= beat_n and half < beat_n + int(rate * 0.18):
			var ot := float(half - beat_n) / float(rate)
			v += 0.30 * sin(TAU * 55.0 * ot) * exp(-ot * 12.0)
		data.encode_s16(i * 2, int(clampf(v, -1.0, 1.0) * 32767.0))
	var wav := AudioStreamWAV.new()
	wav.format = AudioStreamWAV.FORMAT_16_BITS
	wav.mix_rate = rate
	wav.stereo = false
	wav.data = data
	wav.loop_mode = AudioStreamWAV.LOOP_FORWARD
	wav.loop_begin = 0
	wav.loop_end = n
	return wav


# -- volume API (persisted; wire these to the settings row) --
func set_sfx_volume(v: float) -> void:
	sfx_volume = clampf(v, 0.0, 1.0)
	_save_settings()


func set_music_volume(v: float) -> void:
	music_volume = clampf(v, 0.0, 1.0)
	if _music.playing:
		_music.volume_db = _vol_db(music_volume) - _duck_level
	_save_settings()


func set_sfx_enabled(b: bool) -> void:
	sfx_enabled = b
	_save_settings()


func set_music_enabled(b: bool) -> void:
	music_enabled = b
	if not b:
		_music.stop()
		if _drive != null:
			_drive.stop()
	elif _music.stream != null:
		_music.volume_db = _vol_db(music_volume)
		_music.play()
		set_intensity(_intensity)  # re-apply the drive layer
	_save_settings()


func get_sfx_volume() -> float:
	return sfx_volume


func get_music_volume() -> float:
	return music_volume


func is_sfx_enabled() -> bool:
	return sfx_enabled


func is_music_enabled() -> bool:
	return music_enabled


func _vol_db(v: float) -> float:
	return linear_to_db(maxf(v, 0.0001))


func _load_settings() -> void:
	var cfg := ConfigFile.new()
	if cfg.load(SETTINGS_PATH) != OK:
		return
	sfx_volume = clampf(float(cfg.get_value("audio", "sfx_volume", 0.8)), 0.0, 1.0)
	music_volume = clampf(float(cfg.get_value("audio", "music_volume", 0.8)), 0.0, 1.0)
	sfx_enabled = bool(cfg.get_value("audio", "sfx_enabled", true))
	music_enabled = bool(cfg.get_value("audio", "music_enabled", true))


func _save_settings() -> void:
	var cfg := ConfigFile.new()
	cfg.load(SETTINGS_PATH)  # keep other sections (e.g. [room]) intact
	cfg.set_value("audio", "sfx_volume", sfx_volume)
	cfg.set_value("audio", "music_volume", music_volume)
	cfg.set_value("audio", "sfx_enabled", sfx_enabled)
	cfg.set_value("audio", "music_enabled", music_enabled)
	cfg.save(SETTINGS_PATH)
